package com.example.threatfixture.config;

import java.nio.file.Files;
import java.nio.file.Paths;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer implements ApplicationRunner {
    private final JdbcTemplate jdbcTemplate;
    private final AppProperties appProperties;

    public DatabaseInitializer(JdbcTemplate jdbcTemplate, AppProperties appProperties) {
        this.jdbcTemplate = jdbcTemplate;
        this.appProperties = appProperties;
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        Files.createDirectories(Paths.get(appProperties.getUploadRoot()));

        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS users (username VARCHAR(64) PRIMARY KEY, password VARCHAR(128), role VARCHAR(32))");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS accounts (id BIGINT PRIMARY KEY, owner VARCHAR(64), email VARCHAR(128), balance_cents BIGINT)");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS api_tokens (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner VARCHAR(64), provider VARCHAR(64), token_value VARCHAR(512))");
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS webhook_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id BIGINT, amount_cents BIGINT, external_reference VARCHAR(128))");

        jdbcTemplate.update("DELETE FROM webhook_events");
        jdbcTemplate.update("DELETE FROM api_tokens");
        jdbcTemplate.update("DELETE FROM accounts");
        jdbcTemplate.update("DELETE FROM users");

        jdbcTemplate.update("INSERT INTO users (username, password, role) VALUES (?, ?, ?)", "alice", "password123", "USER");
        jdbcTemplate.update("INSERT INTO users (username, password, role) VALUES (?, ?, ?)", "bob", "correct-horse", "USER");
        jdbcTemplate.update("INSERT INTO users (username, password, role) VALUES (?, ?, ?)", "settlement-admin", "admin-local", "ADMIN");

        jdbcTemplate.update("INSERT INTO accounts (id, owner, email, balance_cents) VALUES (?, ?, ?, ?)", 1001L, "alice", "alice@example.test", 125000L);
        jdbcTemplate.update("INSERT INTO accounts (id, owner, email, balance_cents) VALUES (?, ?, ?, ?)", 1002L, "bob", "bob@example.test", 87000L);

        jdbcTemplate.update("INSERT INTO api_tokens (owner, provider, token_value) VALUES (?, ?, ?)", "alice", "acme-payments", "sk_live_fixture_alice_plaintext");
        jdbcTemplate.update("INSERT INTO api_tokens (owner, provider, token_value) VALUES (?, ?, ?)", "bob", "acme-payments", "sk_live_fixture_bob_plaintext");
    }
}
