server {
    listen 80;
    server_name _;

    proxy_set_header X-Forwarded-Proto http;
    proxy_set_header X-Forwarded-Host $host;

    location / {
        proxy_pass http://threat-fixture:8080;
    }

    location /h2-console/ {
        proxy_pass http://threat-fixture:8080/h2-console/;
    }

    location /actuator/ {
        proxy_pass http://threat-fixture:8080/actuator/;
    }
}

